import { Product } from '../models/product.model';

function img(seed: string, n: number): string[] {
  return Array.from({ length: n }, (_, i) => `https://picsum.photos/seed/${seed}-${i}/700/700`);
}

const commonFaq = [
  { question: 'Qual o prazo de entrega?', answer: 'Entrega padrão de 5 a 10 dias úteis ou expressa de 2 a 4 dias úteis, dependendo da sua região.' },
  { question: 'Posso trocar ou devolver o produto?', answer: 'Sim, você tem até 7 dias corridos após o recebimento para solicitar troca ou devolução, sem custo.' },
  { question: 'O produto tem garantia?', answer: 'Sim, todos os produtos possuem garantia de 12 meses direto com a Nexus Store.' },
];

export const PRODUCTS_SEED: Product[] = [
  {
    id: 'headset-gamer-pro-71',
    name: 'Headset Gamer Pro 7.1',
    category: 'Periféricos',
    price: 299.9,
    originalPrice: 399.9,
    images: img('headset-pro', 5),
    description: 'O Headset Gamer Pro 7.1 foi desenvolvido para oferecer a melhor experiência sonora em seus jogos. Com som surround 7.1 real, você escuta cada detalhe e tem vantagem sobre seus adversários. Microfone com cancelamento de ruído para comunicação clara em equipe e conforto para longas sessões de jogo.',
    features: [
      'Som Surround 7.1 Real',
      'Microfone com Cancelamento de Ruído',
      'Iluminação RGB Personalizável',
      'Conforto para Longas Sessões',
      'Compatível com PC, PS4, PS5, Xbox e Switch',
    ],
    specs: [
      { label: 'Conexão', value: 'USB / P2 3.5mm' },
      { label: 'Driver', value: '50mm Neodímio' },
      { label: 'Cabo', value: '2.2m trançado' },
      { label: 'Peso', value: '320g' },
      { label: 'Cor', value: 'Preto com RGB' },
    ],
    rating: 4.6,
    reviewsCount: 128,
    reviews: [
      { id: 'r1', author: 'Lucas M.', rating: 5, comment: 'Som excelente, microfone muito claro. Recomendo demais!', date: '2026-06-02' },
      { id: 'r2', author: 'Fernanda O.', rating: 4, comment: 'Muito confortável, uso por horas sem cansar. Só achei o cabo um pouco curto.', date: '2026-05-14' },
      { id: 'r3', author: 'Rafael T.', rating: 5, comment: 'Melhor custo-benefício da categoria, RGB muito bonito.', date: '2026-04-28' },
    ],
    stock: 42,
    badge: 'mais-vendido',
    exclusive: false,
    faq: commonFaq,
    soldBy: 'Nexus Store',
    freeShipping: true,
  },
  {
    id: 'teclado-mecanico-rgb',
    name: 'Teclado Mecânico RGB',
    category: 'Periféricos',
    price: 399.9,
    originalPrice: 459.9,
    images: img('teclado-rgb', 4),
    description: 'Teclado mecânico com switches responsivos e iluminação RGB totalmente customizável. Estrutura em alumínio escovado para maior durabilidade e teclas com sensação premium em cada toque.',
    features: [
      'Switches Mecânicos Blue',
      'Iluminação RGB Chroma',
      'Estrutura em Alumínio',
      'Anti-ghosting Total',
      'Teclas removíveis para limpeza',
    ],
    specs: [
      { label: 'Switch', value: 'Blue mecânico' },
      { label: 'Layout', value: 'ABNT2' },
      { label: 'Conexão', value: 'USB-C destacável' },
      { label: 'Iluminação', value: 'RGB 16.8M cores' },
    ],
    rating: 4.4,
    reviewsCount: 96,
    reviews: [
      { id: 'r1', author: 'Bruno C.', rating: 5, comment: 'Feedback tátil excelente, som gostoso de digitar.', date: '2026-05-20' },
      { id: 'r2', author: 'Marina S.', rating: 4, comment: 'Muito bom, só é um pouco alto para escritório.', date: '2026-05-02' },
    ],
    stock: 30,
    badge: null,
    exclusive: false,
    faq: commonFaq,
    soldBy: 'Nexus Store',
    freeShipping: true,
  },
  {
    id: 'mouse-gamer-ultra',
    name: 'Mouse Gamer Ultra',
    category: 'Periféricos',
    price: 159.9,
    originalPrice: 199.9,
    images: img('mouse-ultra', 4),
    description: 'Sensor óptico de alta precisão com até 12.000 DPI ajustáveis. Design ergonômico pensado para sessões longas de jogo, com botões laterais programáveis e pés em teflon para deslize suave.',
    features: [
      'Sensor Óptico 12.000 DPI',
      '6 Botões Programáveis',
      'Design Ergonômico',
      'Iluminação RGB',
      'Pés em Teflon',
    ],
    specs: [
      { label: 'DPI', value: 'Até 12.000' },
      { label: 'Botões', value: '6 programáveis' },
      { label: 'Conexão', value: 'USB com fio' },
      { label: 'Peso', value: '95g' },
    ],
    rating: 4.7,
    reviewsCount: 74,
    reviews: [
      { id: 'r1', author: 'Gabriel P.', rating: 5, comment: 'Extremamente leve e preciso, perfeito para FPS.', date: '2026-06-10' },
    ],
    stock: 58,
    badge: 'mais-vendido',
    exclusive: false,
    faq: commonFaq,
    soldBy: 'Nexus Store',
    freeShipping: true,
  },
  {
    id: 'mousepad-gamer-xxl',
    name: 'Mousepad Gamer XXL',
    category: 'Acessórios',
    price: 89.9,
    originalPrice: 119.9,
    images: img('mousepad-xxl', 3),
    description: 'Mousepad extra grande cobrindo mouse e teclado, com base emborrachada antiderrapante e costura reforçada nas bordas para não desfiar com o tempo.',
    features: ['Tamanho XXL 900x400mm', 'Base Antiderrapante', 'Bordas Costuradas', 'Superfície de Controle'],
    specs: [
      { label: 'Dimensões', value: '900 x 400 x 4mm' },
      { label: 'Material', value: 'Tecido + borracha' },
    ],
    rating: 4.5,
    reviewsCount: 51,
    reviews: [
      { id: 'r1', author: 'Igor A.', rating: 5, comment: 'Tamanho perfeito, cobre teclado e mouse com sobra.', date: '2026-05-30' },
    ],
    stock: 80,
    badge: null,
    exclusive: false,
    faq: commonFaq,
    soldBy: 'Nexus Store',
    freeShipping: false,
  },
  {
    id: 'smartwatch-horizon-pro',
    name: 'Smartwatch Horizon Pro Active',
    category: 'Wearables',
    price: 899.9,
    originalPrice: 1199.0,
    images: img('smartwatch-horizon', 4),
    description: 'Monitore sua saúde e performance com o Horizon Pro Active: batimentos cardíacos, oxigenação, sono e mais de 100 modos esportivos. Tela AMOLED de alto brilho e bateria para até 14 dias.',
    features: [
      'Tela AMOLED 1.43"',
      'Bateria de até 14 dias',
      '100+ Modos Esportivos',
      'Resistente à água 5ATM',
      'Monitor cardíaco e de O2',
    ],
    specs: [
      { label: 'Tela', value: 'AMOLED 1.43"' },
      { label: 'Bateria', value: 'Até 14 dias' },
      { label: 'Resistência', value: '5ATM' },
      { label: 'Compatibilidade', value: 'Android e iOS' },
    ],
    rating: 4.8,
    reviewsCount: 42,
    reviews: [
      { id: 'r1', author: 'Carla V.', rating: 5, comment: 'Bateria dura mesmo, uso a semana toda sem carregar.', date: '2026-06-01' },
    ],
    stock: 25,
    badge: 'novo',
    exclusive: false,
    faq: commonFaq,
    soldBy: 'Nexus Store',
    freeShipping: true,
  },
  {
    id: 'headphone-bluetooth-studio-anc',
    name: 'Headphone Bluetooth Studio ANC',
    category: 'Áudio',
    price: 549.9,
    originalPrice: 699.0,
    images: img('headphone-studio', 4),
    description: 'Cancelamento de ruído ativo de estúdio, drivers de 40mm para graves profundos e até 30 horas de bateria. Ideal para viagens, trabalho e imersão total na música.',
    features: ['Cancelamento de Ruído Ativo', 'Até 30h de bateria', 'Drivers 40mm', 'Modo Transparência', 'Dobrável'],
    specs: [
      { label: 'Bateria', value: 'Até 30h com ANC' },
      { label: 'Conexão', value: 'Bluetooth 5.3' },
      { label: 'Driver', value: '40mm' },
    ],
    rating: 4.3,
    reviewsCount: 19,
    reviews: [
      { id: 'r1', author: 'Yasmin R.', rating: 4, comment: 'ANC muito bom, isola bem o ruído do ambiente.', date: '2026-05-18' },
    ],
    stock: 20,
    badge: null,
    exclusive: false,
    faq: commonFaq,
    soldBy: 'Nexus Store',
    freeShipping: true,
  },
  {
    id: 'mouse-gamer-rgb-ultraleve',
    name: 'Mouse Gamer RGB Ultraleve 16000 DPI',
    category: 'Periféricos',
    price: 259.9,
    originalPrice: 320.0,
    images: img('mouse-ultraleve', 4),
    description: 'Apenas 65g com estrutura vazada (honeycomb), sensor de 16.000 DPI e switches óticos de altíssima durabilidade. Feito para os jogadores mais competitivos.',
    features: ['Estrutura Honeycomb 65g', 'Sensor 16.000 DPI', 'Switches Óticos', 'Cabo Paracord Flexível'],
    specs: [
      { label: 'Peso', value: '65g' },
      { label: 'DPI', value: 'Até 16.000' },
      { label: 'Switches', value: 'Óticos 80M cliques' },
    ],
    rating: 4.9,
    reviewsCount: 88,
    reviews: [
      { id: 'r1', author: 'Diego F.', rating: 5, comment: 'Ultraleve mesmo, mudou meu jogo competitivo.', date: '2026-06-05' },
    ],
    stock: 33,
    badge: 'mais-vendido',
    exclusive: false,
    faq: commonFaq,
    soldBy: 'Nexus Store',
    freeShipping: true,
  },
  {
    id: 'notebook-nexus-flow-14',
    name: 'Notebook Nexus Flow 14"',
    category: 'Computadores',
    price: 4299.0,
    originalPrice: 4999.0,
    images: img('notebook-flow', 5),
    description: 'Leve, potente e silencioso. O Nexus Flow 14" traz processador de última geração, tela IPS Full HD e SSD ultrarrápido para produtividade e jogos leves no dia a dia.',
    features: ['Tela IPS Full HD 14"', 'SSD NVMe 512GB', '16GB RAM', 'Até 10h de bateria', 'Teclado retroiluminado'],
    specs: [
      { label: 'Processador', value: 'Octa-core 3.2GHz' },
      { label: 'Memória', value: '16GB LPDDR5' },
      { label: 'Armazenamento', value: '512GB SSD NVMe' },
      { label: 'Tela', value: '14" IPS Full HD' },
    ],
    rating: 4.6,
    reviewsCount: 37,
    reviews: [
      { id: 'r1', author: 'Priscila N.', rating: 5, comment: 'Rápido, silencioso e leve para carregar todos os dias.', date: '2026-05-25' },
    ],
    stock: 12,
    badge: 'novo',
    exclusive: false,
    faq: commonFaq,
    soldBy: 'Nexus Store',
    freeShipping: true,
  },
  {
    id: 'camiseta-nexus-gamer',
    name: 'Camiseta Nexus Gamer Edition',
    category: 'Vestuário',
    price: 79.9,
    originalPrice: 99.9,
    images: img('camiseta-gamer', 3),
    description: 'Camiseta 100% algodão premium com estampa exclusiva Nexus. Corte moderno e caimento confortável para o dia a dia.',
    features: ['100% Algodão Premium', 'Estampa Exclusiva', 'Corte Moderno'],
    specs: [
      { label: 'Material', value: '100% algodão' },
      { label: 'Tamanhos', value: 'P, M, G, GG' },
    ],
    rating: 4.5,
    reviewsCount: 21,
    reviews: [
      { id: 'r1', author: 'Otávio L.', rating: 4, comment: 'Tecido bom, veste bem. Recomendo pedir um tamanho acima.', date: '2026-04-30' },
    ],
    stock: 60,
    badge: null,
    exclusive: false,
    faq: commonFaq,
    soldBy: 'Nexus Store',
    freeShipping: false,
  },
  {
    id: 'cadeira-gamer-nexus-throne',
    name: 'Cadeira Gamer Nexus Throne',
    category: 'Móveis',
    price: 1299.9,
    originalPrice: 1599.9,
    images: img('cadeira-throne', 4),
    description: 'Ergonomia de alto padrão com apoio lombar e de nuca ajustáveis, reclínio de até 165° e revestimento premium que garante conforto em maratonas de jogo ou trabalho.',
    features: ['Reclínio até 165°', 'Apoio Lombar Ajustável', 'Braços 4D', 'Revestimento Premium'],
    specs: [
      { label: 'Peso suportado', value: 'Até 130kg' },
      { label: 'Reclínio', value: 'Até 165°' },
      { label: 'Material', value: 'Couro sintético premium' },
    ],
    rating: 4.7,
    reviewsCount: 29,
    reviews: [
      { id: 'r1', author: 'Henrique B.', rating: 5, comment: 'Conforto absurdo, dores nas costas sumiram.', date: '2026-05-11' },
    ],
    stock: 8,
    badge: 'exclusivo',
    exclusive: true,
    faq: commonFaq,
    soldBy: 'Nexus Store',
    freeShipping: true,
  },
  {
    id: 'teclado-nexus-vip-edition',
    name: 'Teclado Nexus VIP Edition',
    category: 'Periféricos',
    price: 699.9,
    originalPrice: 899.9,
    images: img('teclado-vip', 4),
    description: 'Edição limitada exclusiva para membros Nexus VIP. Corpo em alumínio aeronáutico, switches customizados e caixa de colecionador numerada.',
    features: ['Edição Limitada e Numerada', 'Corpo em Alumínio Aeronáutico', 'Switches Customizados Nexus', 'Caixa de Colecionador'],
    specs: [
      { label: 'Switch', value: 'Nexus Custom Tactile' },
      { label: 'Material', value: 'Alumínio aeronáutico' },
      { label: 'Edição', value: 'Limitada e numerada' },
    ],
    rating: 5.0,
    reviewsCount: 14,
    reviews: [
      { id: 'r1', author: 'Vinícius K.', rating: 5, comment: 'Peça de colecionador, qualidade impecável.', date: '2026-06-08' },
    ],
    stock: 6,
    badge: 'exclusivo',
    exclusive: true,
    faq: commonFaq,
    soldBy: 'Nexus Store',
    freeShipping: true,
  },
  {
    id: 'fone-nexus-elite-anc',
    name: 'Fone Nexus Elite ANC Wireless',
    category: 'Áudio',
    price: 899.9,
    originalPrice: 1099.9,
    images: img('fone-elite', 4),
    description: 'Linha exclusiva Nexus Elite com áudio hi-res, cancelamento de ruído adaptativo e case de carregamento premium em alumínio escovado.',
    features: ['Áudio Hi-Res Certificado', 'ANC Adaptativo', 'Case em Alumínio', 'Bateria total de 36h'],
    specs: [
      { label: 'Bateria total', value: '36h com case' },
      { label: 'Certificação', value: 'Hi-Res Audio' },
    ],
    rating: 4.9,
    reviewsCount: 22,
    reviews: [
      { id: 'r1', author: 'Amanda G.', rating: 5, comment: 'Qualidade de som impressionante, vale o investimento.', date: '2026-05-27' },
    ],
    stock: 10,
    badge: 'exclusivo',
    exclusive: true,
    faq: commonFaq,
    soldBy: 'Nexus Store',
    freeShipping: true,
  },
  {
    id: 'capinha-iphone-nexus-play',
    name: 'Capa Premium Nexus Play',
    category: 'Acessórios',
    price: 69.9,
    originalPrice: 89.9,
    images: img('capa-nexus-play', 3),
    description: 'Capa com proteção anti-impacto em todas as bordas, design exclusivo Nexus Play e acabamento fosco antiderrapante.',
    features: ['Proteção Anti-impacto', 'Design Exclusivo', 'Acabamento Fosco'],
    specs: [
      { label: 'Material', value: 'TPU + policarbonato' },
      { label: 'Compatibilidade', value: 'Diversos modelos' },
    ],
    rating: 4.4,
    reviewsCount: 33,
    reviews: [
      { id: 'r1', author: 'Sofia D.', rating: 4, comment: 'Encaixe perfeito e design muito bonito.', date: '2026-05-03' },
    ],
    stock: 90,
    badge: null,
    exclusive: false,
    faq: commonFaq,
    soldBy: 'Nexus Store',
    freeShipping: false,
  },
];
